name: Publish to GPR

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Create the package
      run: dotnet pack --configuration Release
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: FSharp.AsyncExtra
        # Directory containing files to upload
        path: src/AsyncExtra/bin/Release/
        
        
  publish:
    runs-on: ubuntu-latest
    needs: 
    - build
    steps:
    - uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with: 
        # Artifact name
        name: FSharp.AsyncExtra
        path: Release
    - name: Setup .NET Core
      with:
        dotnet-version: 3.1.201
        source-url: https://nuget.pkg.github.com/insurello/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} github
      uses: actions/setup-dotnet@v1
    - name: Publish the package to GPR
      run: dotnet nuget push Release/*.nupkg


